name: "Release"

on:
  push:
    tags:
      - 'v*' # 只有当你推送以 v 开头的标签（如 v1.0.1）时，才会自动触发打包
  workflow_dispatch: # 允许你在网页上点击按钮手动触发

jobs:
  build-and-release:
    permissions:
      contents: write # 允许脚本创建 Release 和上传文件
    strategy:
      fail-fast: true

    runs-on: windows-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: 配置 Rust
        uses: dtolnay/rust-toolchain@stable

      - name: 安装前端依赖
        run: npm install

      - name: Tauri 自动编译并上传 Release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'ValoCompAnalyser ${{ github.ref_name }}'
          releaseBody: |
            | 平台 | 安装方式 |
            | :--: | -------- |
            | Windows | 下载 `.msi` 或 `.exe` 双击安装 |
            | Android | 下载 APK 直装 |
          releaseDraft: true
          prerelease: false
